name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  php:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        prefer: ['lowest', 'stable']

    steps:
      - uses: actions/checkout@v2

      - name: Switch PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          echo ${{ matrix.php }} > .php-version
          php -v

      - uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer v2
        run: sudo composer self-update --2

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo ${HOME}/.symfony/bin >> $GITHUB_PATH

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-all

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Update dependencies
        run: composer update --prefer-${{ matrix.prefer }} --prefer-dist --no-progress --no-suggest --no-scripts

      - name: PHPunit
        run: ./vendor/bin/phpunit


  sylius:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        sylius: ['1.8', '1.9', '1.10']
        mysql_version: ['5.7', '8.0']
        flex: ["standalone", "official"]
        exclude:
          - php: '8.0'
            sylius: '1.8'
          - php: '8.0'
            sylius: '1.9'

    steps:
      - name: Define SYMFONY_ENDPOINT
        if: matrix.flex == 'standalone'
        run: |
          echo "SYMFONY_ENDPOINT=http://127.0.0.1/" >> $GITHUB_ENV

      - name: Switch PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          echo "date.timezone=UTC" >> /tmp/timezone.ini
          sudo mv /tmp/timezone.ini /etc/php/${{ matrix.php }}/cli/conf.d/timezone.ini
          echo ${{ matrix.php }} > .php-version

      - uses: actions/checkout@v2
        with:
          path: plugin

      # Run the server at the start so it can download the recipes!
      - name: Run standalone symfony flex server
        if: matrix.flex == 'standalone'
        run: |
          echo ${{ github.token }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run --rm --name flex -d -v $PWD/plugin/recipe:/var/www/flex/var/repo/private/monsieurbiz/sylius-alert-message-plugin -p 80:80 docker.pkg.github.com/monsieurbiz/docker/symfony-flex-server:latest contrib official
          docker ps

      - uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer v2
        run: sudo composer self-update --2

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo ${HOME}/.symfony/bin >> $GITHUB_PATH

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Install Sylius-Standard
        run: |
          composer create-project --prefer-dist --no-scripts --no-progress sylius/sylius-standard sylius "~${{ matrix.sylius }}.0"

      - name: Init database
        working-directory: ./sylius
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migr:migr -n

      - name: Setup some requirements
        working-directory: ./sylius
        run: |
          composer config repositories.plugin '{"type": "path", "url": "../plugin/"}'
          composer config extra.symfony.allow-contrib true
          composer config secure-http false
          composer config --unset platform.php

      - name: Install plugin
        working-directory: ./sylius
        run: |
          composer require monsieurbiz/sylius-alert-message-plugin="*@dev"

      - name: Show flex server logs
        if: matrix.flex == 'standalone'
        run: docker logs --tail 100 flex

      - name: Update database schema
        working-directory: ./sylius
        run: |
          php bin/console doctrine:migr:migr -n

      - name: Install Sylius
        working-directory: ./sylius
        run: php bin/console sylius:install -n

    services:

      database:
        image: percona:${{ matrix.mysql_version }}
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
